#!/usr/bin/env ruby
require File.expand_path('../../config/environment',  __FILE__)

require "nokogiri"
require "logger"

loader = ShivaLoader.new
loader.logger = Logger.new(STDOUT)

ARGV.each do |file_name|
  File.open(file_name) do |xml|
    loader.load(xml)
  end
end

p loader.book
