#!/usr/bin/env ruby
require File.expand_path('../../config/environment',  __FILE__)

require "nokogiri"

ARGV.each do |file_name|
  File.open(file_name) do |xml|
    doc = Nokogiri::XML.parse(xml)
    doc.xpath("/book-content/content").each do |content_element|
      p content_element.xpath("sections//title").map(&:text)
      p content_element.xpath("body").text
    end
  end
end
