#!/usr/bin/env ruby
require File.expand_path('../../config/environment',  __FILE__)

require "nokogiri"

loader = ShivaLoader.new

ARGV.each do |file_name|
  File.open(file_name) do |xml|
    loader.load(xml)
  end
end

p loader.book
